import {
  Skill,
  JobLevel,
  JobModality,
  JobStatus,
  JobType,
  CompanySize,
} from "@/database/generated/enums";

export const skillMapper: Record<Skill, string> = {
  JAVASCRIPT: "JavaScript",
  TYPESCRIPT: "TypeScript",
  REACT: "React",
  VUE: "Vue.js",
  ANGULAR: "Angular",
  SVELTE: "Svelte",
  NEXTJS: "Next.js",
  NUXT: "Nuxt.js",
  NEXT: "Next",
  NEST: "NestJS",
  REMIX: "Remix",
  ASTRO: "Astro",
  HTML: "HTML5",
  CSS: "CSS3",
  TAILWINDCSS: "Tailwind CSS",
  SCSS: "SCSS",
  BOOTSTRAP: "Bootstrap",
  SASS: "Sass",
  LESS: "Less",
  WEBPACK: "Webpack",
  VITE: "Vite",
  BUN: "Bun",

  NODEJS: "Node.js",
  PYTHON: "Python",
  JAVA: "Java",
  CSHARP: "C#",
  GOLANG: "Go",
  RUST: "Rust",
  RUBY: "Ruby",
  PHP: "PHP",
  LARAVEL: "Laravel",
  DJANGO: "Django",
  FLASK: "Flask",
  FASTAPI: "FastAPI",
  SPRING: "Spring Boot",
  DOTNET: ".NET",
  CPP: "C++",
  C: "C",
  R: "R",

  POSTGRESQL: "PostgreSQL",
  MYSQL: "MySQL",
  MONGODB: "MongoDB",
  REDIS: "Redis",
  FIREBASE: "Firebase",
  DYNAMODB: "DynamoDB",
  ORACLE: "Oracle",
  ELASTICSEARCH: "Elasticsearch",
  CASSANDRA: "Cassandra",
  MARIADB: "MariaDB",

  REACT_NATIVE: "React Native",
  FLUTTER: "Flutter",
  SWIFT: "Swift",
  KOTLIN: "Kotlin",
  XAMARIN: "Xamarin",
  IONIC: "Ionic",

  DOCKER: "Docker",
  KUBERNETES: "Kubernetes",
  AWS: "AWS",
  AZURE: "Azure",
  GCP: "Google Cloud",
  HEROKU: "Heroku",
  NETLIFY: "Netlify",
  VERCEL: "Vercel",
  GITLAB_CI: "GitLab CI",
  GITHUB_ACTIONS: "GitHub Actions",
  JENKINS: "Jenkins",
  TERRAFORM: "Terraform",

  GIT: "Git",
  GITHUB: "GitHub",
  GITLAB: "GitLab",
  BITBUCKET: "Bitbucket",
  JIRA: "Jira",
  FIGMA: "Figma",
  LINUX: "Linux",
  WINDOWS: "Windows",
  MACOS: "macOS",

  JEST: "Jest",
  VITEST: "Vitest",
  CYPRESS: "Cypress",
  SELENIUM: "Selenium",
  MOCHA: "Mocha",
  CHAI: "Chai",
  PYTEST: "PyTest",
  UNITTEST: "UnitTest",

  REST_API: "REST API",
  GRAPHQL: "GraphQL",
  GRPC: "gRPC",
  WEBSOCKETS: "WebSockets",
  OAUTH: "OAuth",
  JWT: "JWT",
  SQL: "SQL",
  NOSQL: "NoSQL",
  MQ: "Message Queue",
  RABBITMQ: "RabbitMQ",
  KAFKA: "Apache Kafka",
  REDIS_CACHE: "Redis Cache",
  DESIGN_PATTERNS: "Design Patterns",
  AGILE: "Ágil",
  SCRUM: "Scrum",
  MICROSERVICES: "Microsserviços",
  MONOLITH: "Monólito",
  ARCHITECTURE: "Arquitetura de Software",
};

export const jobLevelMapper: Record<JobLevel, string> = {
  ESTAGIÁRIO: "Estágio",
  JÚNIOR: "Júnior",
  PLENO: "Pleno",
  SÊNIOR: "Sênior",
};

export const jobModalityMapper: Record<JobModality, string> = {
  REMOTO: "Remoto",
  HÍBRIDO: "Híbrido",
  PRESENCIAL: "Presencial",
};

export const jobTypeMapper: Record<JobType, string> = {
  INTEGRAL: "Tempo Integral",
  MEIO_PERÍODO: "Meio Período",
  FREELANCER: "Freelancer",
};

export const jobStatusMapper: Record<JobStatus, string> = {
  ABERTA: "Aberta",
  FECHADA: "Fechada",
  PAUSADA: "Pausada",
};

export const companySizeMapper: Record<CompanySize, string> = {
  STARTUP: "Startup",
  PEQUENA: "Pequena empresa",
  MÉDIA: "Média empresa",
  GRANDE: "Grande empresa",
  MULTINACIONAL: "Multinacional",
};
